#!/usr/bin/env bash
# AI Shield — EC2 Stockholm Deployment Script
# =============================================
# Deploys AI Shield to AWS EC2 at 13.50.16.19
# Same server as ThreatFade and FusionOps.
#
# Port: 8002 (ThreatFade: 8000, FusionOps: 8080)
# Nginx: api.aishield.tinlance.com → localhost:8002
#
# Prerequisites on EC2:
#   - Python 3.12, pip, git
#   - PostgreSQL 16 (shared with other Tinlance services)
#   - Redis (shared)
#   - Nginx
#   - certbot (for SSL)
#
# Usage:
#   chmod +x scripts/deploy.sh
#   ./scripts/deploy.sh [production|staging]

set -euo pipefail

ENV="${1:-production}"
EC2_HOST="13.50.16.19"
APP_DIR="/opt/tinlance/ai-shield"
SERVICE_NAME="ai-shield"
PORT=8002
DOMAIN="api.aishield.tinlance.com"

echo ""
echo "🛡️  AI Shield — EC2 Deploy"
echo "=========================="
echo "   Environment: $ENV"
echo "   Host:        $EC2_HOST"
echo "   Port:        $PORT"
echo "   Domain:      $DOMAIN"
echo ""

# ── 1. Pull latest code ───────────────────────────────────────────────────────
echo "→ Pulling latest code from GitHub..."
if [ -d "$APP_DIR" ]; then
    cd "$APP_DIR" && git pull origin main
else
    git clone https://github.com/Tinlance/ai-shield.git "$APP_DIR"
    cd "$APP_DIR"
fi

# ── 2. Python environment ─────────────────────────────────────────────────────
echo "→ Setting up Python environment..."
if [ ! -d "$APP_DIR/.venv" ]; then
    python3 -m venv "$APP_DIR/.venv"
fi
source "$APP_DIR/.venv/bin/activate"
pip install -r backend/requirements.txt -q

# ── 3. Environment file ───────────────────────────────────────────────────────
echo "→ Checking .env file..."
if [ ! -f "$APP_DIR/.env" ]; then
    echo "⚠️  No .env file found! Copy .env.example and fill in values:"
    echo "   cp $APP_DIR/.env.example $APP_DIR/.env"
    echo "   nano $APP_DIR/.env"
    exit 1
fi

# ── 4. Database migration ─────────────────────────────────────────────────────
echo "→ Running database migrations..."
cd "$APP_DIR"
source .env
alembic upgrade head

# ── 5. Systemd service ────────────────────────────────────────────────────────
echo "→ Writing systemd service..."
cat > /etc/systemd/system/${SERVICE_NAME}.service << SERVICE
[Unit]
Description=AI Shield — Runtime AI Security API
After=network.target postgresql.service redis.service
Wants=postgresql.service redis.service

[Service]
Type=simple
User=ubuntu
WorkingDirectory=${APP_DIR}
EnvironmentFile=${APP_DIR}/.env
ExecStart=${APP_DIR}/.venv/bin/uvicorn backend.main:app \
    --host 127.0.0.1 \
    --port ${PORT} \
    --workers 2 \
    --log-level info \
    --access-log
ExecReload=/bin/kill -HUP \$MAINPID
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal
SyslogIdentifier=ai-shield

# Security hardening
NoNewPrivileges=yes
PrivateTmp=yes
ProtectSystem=strict
ReadWritePaths=${APP_DIR}

[Install]
WantedBy=multi-user.target
SERVICE

systemctl daemon-reload
systemctl enable "$SERVICE_NAME"
systemctl restart "$SERVICE_NAME"
echo "   ✅ Service: $SERVICE_NAME started"

# ── 6. Nginx config ───────────────────────────────────────────────────────────
echo "→ Writing Nginx config..."
cat > /etc/nginx/sites-available/${SERVICE_NAME} << NGINX
# AI Shield API — ${DOMAIN}
# Auto-generated by deploy.sh

upstream ai_shield {
    server 127.0.0.1:${PORT};
    keepalive 64;
}

server {
    listen 80;
    server_name ${DOMAIN};

    # Redirect HTTP → HTTPS
    return 301 https://\$server_name\$request_uri;
}

server {
    listen 443 ssl http2;
    server_name ${DOMAIN};

    # SSL (certbot managed)
    ssl_certificate     /etc/letsencrypt/live/${DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${DOMAIN}/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    # Security headers
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Frame-Options DENY always;
    add_header X-Content-Type-Options nosniff always;
    add_header X-Powered-By "" always;

    # Proxy to FastAPI
    location / {
        proxy_pass         http://ai_shield;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade \$http_upgrade;
        proxy_set_header   Connection "upgrade";
        proxy_set_header   Host \$host;
        proxy_set_header   X-Real-IP \$remote_addr;
        proxy_set_header   X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto \$scheme;
        proxy_read_timeout 60s;
        proxy_send_timeout 60s;
    }

    # WebSocket for /monitor/stream
    location /monitor/stream {
        proxy_pass         http://ai_shield;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade \$http_upgrade;
        proxy_set_header   Connection "Upgrade";
        proxy_set_header   Host \$host;
        proxy_read_timeout 86400s;
    }
}
NGINX

ln -sf /etc/nginx/sites-available/${SERVICE_NAME} /etc/nginx/sites-enabled/
nginx -t && systemctl reload nginx
echo "   ✅ Nginx configured for $DOMAIN"

# ── 7. SSL certificate ────────────────────────────────────────────────────────
echo "→ Requesting SSL certificate..."
if [ ! -d "/etc/letsencrypt/live/$DOMAIN" ]; then
    certbot --nginx -d "$DOMAIN" --non-interactive --agree-tos -m nwachukwuchinaemerem8@gmail.com
    echo "   ✅ SSL certificate issued"
else
    echo "   ✅ SSL certificate already exists"
fi

# ── 8. Smoke test ─────────────────────────────────────────────────────────────
echo "→ Running smoke test..."
sleep 3

HEALTH=$(curl -s "https://$DOMAIN/health" 2>/dev/null || echo '{"status":"unreachable"}')
STATUS=$(echo "$HEALTH" | python3 -c "import sys,json; print(json.load(sys.stdin).get('status','error'))" 2>/dev/null || echo "error")

if [[ "$STATUS" == "ok" || "$STATUS" == "degraded" ]]; then
    echo ""
    echo "✅ AI Shield deployed successfully!"
    echo "   API: https://$DOMAIN"
    echo "   Docs: https://$DOMAIN/docs"
    echo "   Status: $STATUS"
    echo ""
    echo "Next:"
    echo "  1. Add .env secrets: nano $APP_DIR/.env"
    echo "  2. Configure Clerk webhook: https://$DOMAIN/webhooks/lemonsqueezy"
    echo "  3. Add API key to Olvrix: AI_SHIELD_API_URL=https://$DOMAIN"
    echo "  4. Run demo: bash $APP_DIR/scripts/demo.sh"
else
    echo ""
    echo "❌ Smoke test failed (status=$STATUS)"
    echo "   Check logs: journalctl -u ai-shield -n 50"
    exit 1
fi
